#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run linting and type-checking
npm run lint

# Run tests that are affected by the changes
npm run test:ci -- --findRelatedTests $(git diff --cached --name-only | grep -E '\.(js|jsx|ts|tsx)$' | xargs)
